In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.5.0'

In [3]:
# Create vector 
vec_tf = tf.constant([1, 2, 3, 5])
vec_tf

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 5])>

In [4]:
vec_tf.ndim

1

In [5]:
# metrics 
metric_tf = tf.constant([[1, 2, 3],
                         [2, 3, 4],
                         [3, 4, 5]])
metric_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])>

In [6]:
metric_tf.ndim

2

In [7]:
# tensor
ten_tf = tf.constant([[[1, 3, 4],
                       [2, 4, 5]],
                      [[3, 5, 6],
                       [4, 6, 7]],
                      [[6, 8, 9],
                       [7, 8, 9]]])
ten_tf

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 3, 4],
        [2, 4, 5]],

       [[3, 5, 6],
        [4, 6, 7]],

       [[6, 8, 9],
        [7, 8, 9]]])>

In [8]:
ten_tf.ndim

3

In [9]:
# variable tensor
vr_ten = tf.Variable([[[1, 3, 4],
                       [2, 4, 5]],
                      [[3, 5, 6],
                       [4, 6, 7]],
                      [[6, 8, 9],
                       [7, 8, 9]]])
vr_ten

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[1, 3, 4],
        [2, 4, 5]],

       [[3, 5, 6],
        [4, 6, 7]],

       [[6, 8, 9],
        [7, 8, 9]]])>

In [10]:
vr_ten.ndim

AttributeError: 'ResourceVariable' object has no attribute 'ndim'

In [11]:
vr_ten[0][0][0] = 4

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [12]:
vr_ten[0][0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
vr_ten[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 4],
       [2, 4, 5]])>

In [14]:
vr_ten.assign([[[1, 2, 3],
                [2, 3, 4]],
               [[3, 4, 5],
                [7, 6, 5]],
               [[3, 2, 1],
                [0, 9, 8]]])

vr_ten

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [7, 6, 5]],

       [[3, 2, 1],
        [0, 9, 8]]])>

In [15]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [16]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [17]:
random_1 = tf.random.shuffle(random_1, seed=34)

In [18]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [19]:
tf.random.set_seed(42)  # global level seed set
tf.random.shuffle(random_1, seed=42) # operational level seed set

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

# Other way to make Tensor

In [20]:
# create tensor with all ones
tf.ones([3, 7]) # or we can use tf.ones(shape=(3, 7))

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
# create tensor with all zeros
tf.zeros([3, 7]) # or we can use tf.ones(shape=(3, 7))

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [22]:
tf.ones(shape=(3, 7)), tf.zeros(shape=(3, 7))

(<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 7), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>)

### Turn Numpy array into tensors

The main differencee between numpy arrays and TensorFlow tensor is that tensors can be run on a GPU (much faster for numerical computing).

In [23]:
# you can also turn NumPy array into tensors
import numpy as np

numpy_a = np.arange(1, 25, dtype=np.int32) # create a numpy array between 1 and 25
numpy_a

# x = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [24]:
a = tf.constant(numpy_a)
a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [25]:
a = tf.constant(numpy_a, shape=(2, 3, 4))
a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [27]:
a.ndim

3

### Getting information from tensor 

When dealing with tensors you probably want to be aware of the following attributes:

* Shape
* Rank
* Axis or Dimension
* Size

In [28]:
# Create a rank 4 tensors (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [35]:
2 * 3 * 4 * 5

120

In [44]:
# Get Various attribute of our tensor
print('Datatypes of every element\t\t:', rank_4_tensor.dtype)
print('Number of dimensions (rank)\t\t:', rank_4_tensor.ndim)
print('Shape of tensor\t\t\t\t:', rank_4_tensor.shape)
print('Elements along the 0 axis\t\t:', rank_4_tensor.shape[0])
print('Elements along the last axis\t\t:', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor\t:', tf.size(rank_4_tensor))
print('Total number of elements in our tensor\t:', tf.size(rank_4_tensor).numpy())

Datatypes of every element		: <dtype: 'float32'>
Number of dimensions (rank)		: 4
Shape of tensor				: (2, 3, 4, 5)
Elements along the 0 axis		: 2
Elements along the last axis		: 5
Total number of elements in our tensor	: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor	: 120


### Indexing Tensor

Tensor can be Indexing just Python lists.

In [46]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [48]:
# get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [53]:
# Get the first elememt from each dimension from each labels except for the final one
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [54]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [56]:
rank_2_tensor.shape, rank_2_tensor.ndim, tf.size(rank_2_tensor), tf.size(rank_2_tensor).numpy()

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>, 4)

In [57]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [58]:
# Get the last item of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [59]:
# Add in extra diemension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # also use `rank_2_tensor[:, :, tf.newaxis]` insted of "..."
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [60]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [62]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

### Manipulating tensors (tensor operations)

**Basic Operation**

`+`, `-`, `*`, `/`

In [2]:
# you can add values to a tensor using the addition operation
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [69]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [66]:
# subtraction
tensor - 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 4],
       [0, 1]])>

In [67]:
# multification
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]])>

In [68]:
# division
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [70]:
# we can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [71]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [72]:
tf.subtract(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 4],
       [0, 1]])>

In [73]:
tf.divide(tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2.5 , 1.75],
       [0.75, 1.  ]])>

In [74]:
# another way to basic operation
tf.math.multiply(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]])>

In [75]:
tf.math.add(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 12],
       [ 8,  9]])>

In [76]:
tf.math.subtract(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]])>

In [80]:
tf.math.divide(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.33333333, 2.33333333],
       [1.        , 1.33333333]])>

**Matrix Multiplication**

In machine learning, metrics multiplication is one of the most common tensor operations.

please visit this website before do programming: http://matrixmultiplication.xyz/

In [4]:
# Metrix Multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [5]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [6]:
# Metrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [7]:
tensor.shape

TensorShape([2, 2])

In [8]:
# create a tensor (3, 2) tensor
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create a tensor (3, 3) tensor
y = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

In [9]:
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>)

In [14]:
tf.matmul(x, y)

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,3] 0 0 [Op:MatMul]

**There are couples rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them:**
1. The inner dimension must match 
2. the resulting matrix has the shape of the inner dimensions

In [11]:
tf.matmul(y, x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])>

In [12]:
y @ x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])>

📖 **Resources:** Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [15]:
tf.reshape(x, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [17]:
tf.reshape(x, shape=(2, 3)) @ y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]])>

In [18]:
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [19]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [22]:
np.transpose(x) @ y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 57, 66],
       [60, 72, 84]])>

In [36]:
tf.transpose(x), tf.reshape(x, shape=(2, 3)), np.transpose(x), x

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 array([[1, 3, 5],
        [2, 4, 6]]),
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>)

**The `dot` product**

Matrix multiplication is also referred to as the dot product.

You can performed matrix multiplication using.
* `tf.matmul()`
* `tf.tesnordot()`
* `@`

In [53]:
# Perform the dot product on x and y (requires x and y to be transposed)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 57, 66],
       [60, 72, 84]])>

In [60]:
tf.tensordot(tf.reshape(x, shape=(2, 3)), y, axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]])>

In [56]:
tf.tensordot(y, x, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])>

**Generally, when performing matrix multiplication of two tensor and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplications rules.**

In [54]:
tf.tensordot(tf.transpose(x), y, axes=0)

<tf.Tensor: shape=(2, 3, 3, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[ 3,  6,  9],
         [12, 15, 18],
         [21, 24, 27]],

        [[ 5, 10, 15],
         [20, 25, 30],
         [35, 40, 45]]],


       [[[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]],

        [[ 4,  8, 12],
         [16, 20, 24],
         [28, 32, 36]],

        [[ 6, 12, 18],
         [24, 30, 36],
         [42, 48, 54]]]])>

In [47]:
np.dot(tf.transpose(x), y)

array([[48, 57, 66],
       [60, 72, 84]])

### Changing the datatype of a tensor

In [65]:
tf.__version__

'2.5.0'

In [62]:
# Create a new tensor with defalut datatype (float32)
b = tf.constant([1.7, 7.4])
b.dtype

tf.float32

In [64]:
c = tf.constant([7, 10])
c.dtype

tf.int32

In [66]:
# change from float32 to float16 (reduced precision)
d = tf.cast(b, dtype=tf.float16)
d

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [79]:
# Change from int32 to int16 (reduced precision)
e = tf.cast(c, dtype=tf.int16)
e

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [109]:
# Get the absolute values
d = tf.constant([-7, -10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [110]:
# Get the absolute values
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Let's go through the following forms of aggregation.
* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of tensor

In [113]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [114]:
# Get the mean in tensor
tf.math.reduce_mean(x)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [115]:
# Get the maximum value in tensor
tf.math.reduce_max(x)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [116]:
# Get the minimum value in tensor
tf.math.reduce_min(x)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [117]:
# Get the sum of all tensor value
tf.math.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [118]:
# Creating a random tensor with values between 0 and 100 of size 50
r = tf.constant(np.random.randint(1, 100, 50))
r

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([18, 24, 98, 55, 87, 76, 81, 36, 49, 71, 56, 30, 62, 62, 89, 50, 46,
       20, 54, 42, 71, 24, 47, 17, 23,  4, 37, 96, 22, 95, 91, 34, 73, 54,
       29, 93, 22, 27, 71, 53, 47, 94, 84, 36, 28, 48, 48,  1, 23, 87])>

In [121]:
r = tf.reshape(r, shape=(5, -1))
r

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[18, 24, 98, 55, 87, 76, 81, 36, 49, 71],
       [56, 30, 62, 62, 89, 50, 46, 20, 54, 42],
       [71, 24, 47, 17, 23,  4, 37, 96, 22, 95],
       [91, 34, 73, 54, 29, 93, 22, 27, 71, 53],
       [47, 94, 84, 36, 28, 48, 48,  1, 23, 87]])>

In [122]:
# Get the maximum number of tensor r
tf.math.reduce_max(r)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [123]:
# Get the minimum number of tensor r
tf.math.reduce_min(r)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [124]:
# Get the mean value of tensor r
tf.math.reduce_mean(r)

<tf.Tensor: shape=(), dtype=int32, numpy=51>

In [125]:
# Get the sum of tensor r
tf.math.reduce_sum(r)

<tf.Tensor: shape=(), dtype=int32, numpy=2585>

In [131]:
r.shape, r.ndim, tf.size(r).numpy()

(TensorShape([5, 10]), 2, 50)

In [139]:
a = tf.reshape(r, shape=(10, 5, 1))
a

<tf.Tensor: shape=(10, 5, 1), dtype=int32, numpy=
array([[[18],
        [24],
        [98],
        [55],
        [87]],

       [[76],
        [81],
        [36],
        [49],
        [71]],

       [[56],
        [30],
        [62],
        [62],
        [89]],

       [[50],
        [46],
        [20],
        [54],
        [42]],

       [[71],
        [24],
        [47],
        [17],
        [23]],

       [[ 4],
        [37],
        [96],
        [22],
        [95]],

       [[91],
        [34],
        [73],
        [54],
        [29]],

       [[93],
        [22],
        [27],
        [71],
        [53]],

       [[47],
        [94],
        [84],
        [36],
        [28]],

       [[48],
        [48],
        [ 1],
        [23],
        [87]]])>

In [141]:
b = tf.reshape(a, shape=(1, 5, 10))
b

<tf.Tensor: shape=(1, 5, 10), dtype=int32, numpy=
array([[[18, 24, 98, 55, 87, 76, 81, 36, 49, 71],
        [56, 30, 62, 62, 89, 50, 46, 20, 54, 42],
        [71, 24, 47, 17, 23,  4, 37, 96, 22, 95],
        [91, 34, 73, 54, 29, 93, 22, 27, 71, 53],
        [47, 94, 84, 36, 28, 48, 48,  1, 23, 87]]])>

In [146]:
(b * a) @ (a * b)

InvalidArgumentError: In[0] mismatch In[1] shape: 10 vs. 5: [10,5,10] [10,5,10] 0 0 [Op:BatchMatMulV2]

In [149]:
tf.transpose(a[0]) @ b[0]

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[17720, 13552, 19181, 10246,  9987, 12251, 11574, 12108, 10240,
        22080]])>

In [150]:
np.max(r)

98

In [151]:
np.min(r)

1

In [154]:
np.mean(r)

51.7

In [153]:
np.median(r)

48.5

In [155]:
np.sum(r)

2585

🛠 **Exercise:** with what we've just learned, find the variance and standard deviation of our `'r'` tensor using Tensorflow methods

In [157]:
tf.math.reduce_max(r).numpy()

98

In [158]:
tf.math.reduce_min(r).numpy()

1

In [165]:
r.ndim

2

In [167]:
tf.math.reduce_euclidean_norm(r, 1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([205, 171, 169, 190, 181])>

In [173]:
tf.math.reduce_prod(r, 1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-1912979968,   858705920,  -726960128,  1154765976,  -286687232])>

In [174]:
tf.math.reduce_sum(r)

<tf.Tensor: shape=(), dtype=int32, numpy=2585>

In [175]:
# Find the varience of our tensor
tf.reduce_varience(r)

AttributeError: module 'tensorflow' has no attribute 'reduce_varience'

In [182]:
import tensorflow_probability as tfp

In [183]:
tfp.stats.variance(r)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 595,  711,  309,  267,  907,  911,  377, 1032,  356,  397])>

In [186]:
r = tf.reshape(r, shape=(50))

In [187]:
r

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([18, 24, 98, 55, 87, 76, 81, 36, 49, 71, 56, 30, 62, 62, 89, 50, 46,
       20, 54, 42, 71, 24, 47, 17, 23,  4, 37, 96, 22, 95, 91, 34, 73, 54,
       29, 93, 22, 27, 71, 53, 47, 94, 84, 36, 28, 48, 48,  1, 23, 87])>

In [188]:
# To find the variance of our tensor we need access to tensorflo_probability
import tensorflow_probability as tfp
tfp.stats.variance(r)

<tf.Tensor: shape=(), dtype=int32, numpy=715>

In [197]:
tfp.stats.variance(tf.cast(r, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=714.93>

In [189]:
# Find the standard deviation
tf.math.reduce_std(r)

TypeError: Input must be either real or complex

In [192]:
tf.math.reduce_std(tf.cast(r, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.738174>

### Find the positional maximum and minimum

In [196]:
tf.math.reduce_variance(tf.cast(r, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=714.93>

In [203]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [205]:
# Find the positional maximum 
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [207]:
# Index on our largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [208]:
# find the max value of "f"
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [210]:
# Check for equlity
f[tf.argmax(f)] == tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [211]:
# Find the positional minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [212]:
# find smallest value on our tensor
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [213]:
# find the small value  of "f"
tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [214]:
# check the equlity 
f[tf.argmin(f)] == tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [216]:
# Create a tensor to get started
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [218]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [219]:
g_squeezed = tf.squeeze(g)
g_squeezed.shape

TensorShape([50])

### One Hot Encoding

In [220]:
# Create a list of reduce
some_list = [0, 1, 2, 3] # could be 'red', 'green', 'blue', 'purple'

# One-Hot encode our list of indices
tf.one_hot(some_list, depth=4) # "depth" : number of unique parameter

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [222]:
# Specify custom values for one-hot encoding 
tf.one_hot(some_list, depth=4, on_value='on', off_value='off')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'on', b'off', b'off', b'off'],
       [b'off', b'on', b'off', b'off'],
       [b'off', b'off', b'on', b'off'],
       [b'off', b'off', b'off', b'on']], dtype=object)>

### Squaring, log, square root

In [223]:
# create a new tensor
h = tf.range(1, 10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [224]:
# square it
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [227]:
# square-root it
tf.sqrt(h)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

**Will Error because `dtype=int32` is not supported for `Square-Root`.**

In [226]:
# square-root it
tf.sqrt(tf.cast(h, dtype=tf.float32)) # that's why I converted to "float32"

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [230]:
# Find the log
tf.math.log(tf.cast(h, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.

In [231]:
# Create a tensor directly from  a numpy array
j = tf.constant(np.array([3., 7., 10.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [232]:
# Convert our tensor back to a NumPy array
np.array(j), type(np.array(j))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [233]:
# Converrt tensor "j" to a NumPy array
j.numpy(), type(j.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [236]:
# The default type of each are slightly different
numpy_j = tf.constant(np.array([3., 7., 10.]))
tensor_j = tf.constant([3., 7., 10.])

# check the datatyped of each
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Wed May 26 10:58:36 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 466.47       Driver Version: 466.47       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8    N/A /  N/A |     45MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------